toDoProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('addTask', views.addTask, name='addTask'),
    path('<int:id>deleteTask', views.deleteTask, name='deleteTask'),
    path('<int:id>updateTask', views.updateTask, name='updateTask'),
]

todo/models.py
from django.db import models

PRIORITY_CHOICES = (
    ('1', "high"),
    ('2', "medium"),
    ('3', "low"),
)

# Create your models here.
class todo(models.Model):
    content = models.CharField(max_length=150)
    priority = models.CharField(max_length = 3, 
        choices = PRIORITY_CHOICES, 
        default = '1')
    on_time = models.TimeField(auto_now_add=True)
    on_date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.id} : {self.content} {self.priority} {self.on_time} {self.on_date}'

todo/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import todo
from django import forms


class addTaskForm(forms.ModelForm):
    class Meta: 
        model = todo 
        fields = "__all__"
        widgets = {
            'content': forms.TextInput(attrs={
                'placeholder': 'Add your task here...',
                'class':'addTaskFormInput' 
            }),
            
        }
        labels = {
        "content": "",
        "priority": "",
    }
    
        
   

class updateTaskForm(forms.ModelForm):
    class Meta: 
        model = todo 
        fields = "__all__"
        labels = {
        "content": "",
        "priority":"",
        }
        widgets = {
            'content': forms.TextInput(attrs={
                'class':'updateTaskFormInput' 
            }),
            
        }

# show tasks/ homepage
def index(request):
    # return render(request, 'todo/index.html', context={
    #     'tasks': todo.objects.all(),
    #     'addTaskForm':addTaskForm()
    # })
    return render(request, 'todo/index.html', context={
        'tasks': todo.objects.all().order_by('priority','-on_time','-on_date'),
        'addTaskForm':addTaskForm()
    })


# add task:
def addTask(request):
    if request.method == 'POST':
        add_task_form = addTaskForm(request.POST) # user filled data form
        if add_task_form.is_valid():
            ntask = add_task_form.cleaned_data['content']
            npriority = add_task_form.cleaned_data['priority']
            # ntime = add_task_form.cleaned_data['on_time']
            # ndate = add_task_form.cleaned_data['on_date']
            obj_todo = todo(content = ntask, priority = npriority)
            obj_todo.save()
            return HttpResponseRedirect(reverse('todo:index'))
        else:
            return render(request, 'todo/index.html', context={
                'addTaskForm':add_task_form 
            })
    # if request.method == 'POST':
    #     ntask = request.POST['content']
    #     obj_todo = todo(content = ntask)
    #     obj_todo.save()
    # return render(request, 'todo/index.html', context={
    #     'tasks': todo.objects.all(),
    # })
    return render(request, 'todo/index.html', context={
        'addTaskForm':addTaskForm()
    })

# delete task:
def deleteTask(request, id):
    task = todo.objects.get(id=id)
    task.delete()
    return render(request, 'todo/index.html', context={
        'tasks': todo.objects.all(),
        'addTaskForm':addTaskForm()
    })

# update tasl:
def updateTask(request, id):
    task = todo.objects.get(id=id)

    if request.method == 'POST':
        updated_form = updateTaskForm(request.POST, instance=task)
        if updated_form.is_valid():
            updated_form.save()
            return HttpResponseRedirect(reverse('todo:index'))

    return render(request, 'todo/update_task.html', context={
        'task':task, #........
        'form': updateTaskForm(instance=task)
    })  

    # return render(request, 'todo/index.html', context={
    #     'task_to_update':task, #........
    #     'update_form': updateTaskForm(request.POST,instance=task),
    # })   

todo/templates/todo/index.html
{% extends 'todo/layout.html' %}   

{% block body %}
        
        <!-- header -->
        <center>
        <div class="card text-white bg-dark mb-3" style="width: 570px; margin-top: 30px; border-radius:10px;">
            <div class="card-header bg-success"><h3><b>To Do App</b></h3></div>
            <div class="card-body">
                <h5 class="card-title"></h5>
                <center>
                    <form action="{% url 'todo:addTask' %}" method="POST">
                        {% csrf_token %}
                        {{addTaskForm}}
                        &nbsp;
                        <input type="submit" class="btn btn-success" style="height:fit-content">
                    </form>
                </center>
            </div>
        



        <center>
        <table class="table table-striped bg-dark text-white" 
              style="height:fit-content; width:570px; border-radius:10px;
              ">
            <!-- <thead style="display: block;">
                <tr style="display: block; ">
                    <th>Priority</th>
                    <th>Task</th>
                    <th>Time</th>
                    <th>Date</th>
                    <th>Update Task</th>
                    <th>Delete Task</th>
                </tr>
            </thead> -->
            <tbody style="
                        display:block;
                        width:570px;
                        overflow: auto;
                        height: 350px;">
            

        {% for task in tasks %}
                <tr>
                    <td>
                        {% if task.priority == '1' %}
                        ✔✔✔
                        {% elif task.priority == '2'%}
                        ✔✔
                        {% elif task.priority == '3'%}
                        ✔
                        {%endif%}
                    </td>
                    <td style="width: 250px;">{{task.content}}</td>
                    <td>{{task.on_time}}</td>
                    <td>{{task.on_date}}</td>

                    <td> 
                        <form action="{% url 'todo:updateTask' task.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value='Update' class="btn btn-warning">


                            <!-- Button trigger modal -->
                            <!-- <button type="button" data-toggle="modal" data-target="#exampleModal{{task.id}}">
                                Update
                            </button> -->
                    
                            <!-- Modal -->
                            <!-- <div class="modal fade" id="exampleModal{{task.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Update Task</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <form action="{% url 'todo:updateTask' task.id %}" method="POST">
                                                {% csrf_token %} 
                                                    {{update_form}}
                                                <input type="submit" value='Save'>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Save changes</button>
                                        </div>
                                    </div>
                                </div>
                            </div> -->


                        </form>
                    </td>
                    <td>
                        <form action="{% url 'todo:deleteTask' task.id %}" method="POST">
                            {% csrf_token %}
                            <input type="submit" value='Delete' class="btn btn-danger">
                        </form>
                    </td>
                </tr>
        {% empty %}
                <tr style="text-align: center; ">
                    <td colspan="6">No tasks !!</td>
                </tr>
        {% endfor %}
        </tbody>
        </table>
        </center>
        
        </div>
        


 
        <!-- <form action="{% url 'todo:addTask' %}" method="POST">
            {% csrf_token %}
            
            <input type="text" name="content" required maxlength="150">
            <input type="submit">
        </form> -->
        

    {% endblock %}

todo/templates/todo/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- for styling addTaskForm -->
    <style>
    .addTaskFormInput{
        width:350px;
        height: 26px;
        background-color: whitesmoke;
        border-radius: 5px;
        border: 2px solid white;
        
    }
    .updateTaskFormInput{
        color: black;
        width: 350px;
        height: 25px;
    }

    </style>

    

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- Optional JavaScript; choose one of the two! -->
    
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    
    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        -->

    <title>Hello, world!</title>
</head>

<body style="background: #466368;
  background: radial-gradient(#648880, #293f50) ">
    
        {% block body %}
        
        {% endblock %}

</body>

</html>

todo/templates/todo/update_task.html
{% extends 'todo/layout.html' %}

{% block body %}



<!-- {{ task_to_be_updated.id }} / {{ task_to_be_updated.content }} / {{ task_to_be_updated.priority }} -->
<center>
<div class="card text-white bg-dark mb-3" style="width: 600px; margin-top: 30px; border-radius:10px;">
    <div class="card-header bg-success">
        <h3><b>Update Tasks</b></h3>
    </div>
    <!-- <div class="card-body">
        <h5 class="card-title"></h5>
        <center>
        </center>
    </div> -->
</div>  

<form action="{% url 'todo:updateTask' task.id %}" method="POST" style="height: 500px;border-radius:10px; ">
    <div style="width:600px; height:100px; padding:30px" class="table-dark">
    {% csrf_token %}
    {{form.as_table}}
    &nbsp;
    <input type="submit" value='Update' class="btn btn-warning" style="height: 40px; font-weight:bold; color:white">
    </div>
</form>


</center>

<!-- {{update_task_form}} -->




{% endblock %}